---
# ansible/roles/tools/vars/main.yml
tool_definitions:
  jq:
    apt: [jq]
    deps: []

  gnupg:
    apt: [gnupg]
    deps: []

  git:
    apt: [git]
    deps: []

  curl:
    apt: [curl]
    deps: []

  wget:
    apt: [wget]
    deps: []

  vim:
    apt: [vim]
    deps: []

  python3-pip:
    apt: [python3-pip]
    deps: []

  pipx:
    apt: [pipx]
    deps: [python3-pip]

  hatch:
    pipx: hatch
    deps: [pipx]

  tea:
    deps: [curl]
    tasks: install-tea.yml

  gh:
    deps: [gnupg]
    tasks: install-gh.yml

  cloudflared:
    deps: [gnupg]
    tasks: install-cloudflared.yml

  docker:
    deps: [gnupg, curl]
    tasks: install-docker.yml
