model_list:
  - model_name: "claude-*"
    litellm_params:
      model: "anthropic/claude-*"
  - model_name: "ollama/*"
    litellm_params:
      model: "ollama_chat/*"
      api_base: "http://192.168.88.144:11434"
