version: "3.8"

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker   # or manager, if you prefer
    environment:
      - LOG_LEVEL=info          # debug, info, warning, error
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none     # can configure hcaptcha / 2captcha
      - PORT=8191
    networks:
      - traefik-net
    ports:
      - "8191:8191"   # if you want it directly exposed, optional
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.services.flaresolverr.loadbalancer.server.port=8191"
      - "traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.schollar.dev`)"
      - "traefik.http.routers.flaresolverr.entrypoints=websecure"
      - "traefik.http.routers.flaresolverr.tls.certresolver=cf"  # if using your Cloudflare certresolver

networks:
  traefik-net:
    external: true

