---
- name: Deploy claude-runner API service
  hosts:
    - claude-nunya
  become: true

  vars:
    required_tools: [tea, jq]

  pre_tasks:
    - name: Install required tools
      import_role:
        name: tools

  roles:
    - runner
