route:
  receiver: default
  group_by: ["alertname", "instance"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 6h

receivers:
  - name: default
    # email_configs: [...]
    # webhook_configs: [{ url: "https://hooks.slack.com/services/..." }]
